### ISSUE TITLE
Traces don't seem to work outside of nom-tracable repository.

### ISSUE THREAD

**Issue by ithinuel** [dalance/nom-tracable#18]
For a reason I cannot explain, running `$ cargo run --manifest-path=nom-tracable/Cargo.toml --example str_parser --features trace` form a local clone of this repository displays the traces as expected (and shown on the readme's screenshot).

But replicating it outside of the repository does not show anything (only the histogram's frame).
Eg running `cargo run` from https://github.com/ithinuel/sandbox/tree/nom-tracable (note it is on the `nom-tracable` branch)

**Comment by ithinuel** [comment]
But adding the extra feature does make it work.

Is that because the code generated by the proc macro relies on feature from the current crate (rather than features from the nom-tracable feature) ?

**Comment by dalance** [comment]
Trace will be shown when `trace` feature of `nom-tracable` is enabled only.
In `Cargo.toml` of your `sandbox`,

```toml
[features]
default = []
trace = ["nom-tracable/trace"]
```

The "trace = ..." line means "If `trace` feature of `sandbox` is specified, `trace` feature of `nom-tracable` will be enabled".
So if you run `cargo run --feature trace` in your repository, trace will be shown.

For example, the following will enable trace by default.

```toml
[features]
default = ["trace"]
trace = ["nom-tracable/trace"]
```
