### ISSUE TITLE
More doc

### ISSUE THREAD

**Issue by Stargateur** [dalance/nom-tracable#3]
Would be nice to have more documentation, I tried to look a the source code but it's quite complex:

* What is the difference between `histogram()` and `cumulative_histogram`.
* Like the crate use a global state, What is exactly show in the histogram output, do we need to reset the state for each time we use a nom parser ? For example, I do some unit test that I want to trace for debug purpose, is each histogram independent for each `TracableInfo` I create or not ?
* I use tokio and so use a lot of futures that each parse a document, is the global state gonna be create for each futures or each thread or none ?

Note: Why a global state is it really needed (noob question) ?

**Comment by dalance** [comment]
> * What is the difference between `histogram()` and `cumulative_histogram`.

`histogram` shows call counts of each parser.
`cumulative_histogram` shows call counts including the counts of children parsers.

For example, the following trace shows `A` is called 1 time, `B` is called 2 times.

```
-> A
  -> B
  <- B
  -> B
  <- B
<- A
```

In this case, `cumulative_histogram` shows `A` is called 1 + 2 = 3 times.
`cumulative_histogram` is useful to find which parser is time-consuming.

> * Like the crate use a global state, What is exactly show in the histogram output, do we need to reset the state for each time we use a nom parser ? For example, I do some unit test that I want to trace for debug purpose, is each histogram independent for each `TracableInfo` I create or not ?

The global state is reset at calling parser with new `TracableInfo`.

```rust
fn main() {
    // Configure trace setting
    let info = TracableInfo::new().parser_width(64).fold("term");
    let _ret = expr(LocatedSpan::new_extra("1-1+1+1-1", info)); // <- reset global state

    // Show histogram
    histogram();
    cumulative_histogram();

    // Configure trace setting
    let info = TracableInfo::new().parser_width(64).fold("term");
    let _ret = expr(LocatedSpan::new_extra("1-1+1+1-1", info)); // <- reset global state

    // Show histogram
    histogram();
    cumulative_histogram();
}
```

> * I use tokio and so use a lot of futures that each parse a document, is the global state gonna be create for each futures or each thread or none ?

The global state uses thread local storage.
So it is each thread.

> Note: Why a global state is it really needed (noob question) ?

I tried to pass the statistics information through parser argument like `nom_locate::LocatedSpan`.
But there is no way to return the information from the failed parser.
So I use global state.

**Comment by Stargateur** [comment]
I think you answer all my questions I wonder if Rust include the static even if trace feature is not activate. But I think the cost it's totally ok.

**Comment by dalance** [comment]
Thanks.
I added some doc comments, and removed unused thread local storage when trace feature is disabled.
