### ISSUE TITLE
Can't use with number nom API

### ISSUE THREAD

**Issue by Stargateur** [dalance/nom-tracable#5]
Unfortunately, it's seem impossible to use [number](https://docs.rs/nom/5.1.2/nom/number/index.html) while using nom-tracable, more a nom issue than a nom-tracable issue.

related: https://github.com/fflorent/nom_locate/issues/35

**Comment by Geal** [comment]
It will be fixed in nom 6 (already visible on github)

**Comment by dalance** [comment]
Now nom is updated to 6.
Thanks!
